/**
 * Central dictionary for all system permissions.
 * Using a Javascript object acts as our Enum, replacing the need for a separate SQL/Mongo table.
 * It provides instant O(1) lookups and avoids expensive DB joins for permission checks.
 */

const ACTIONS = {
  // --- Admin & Global Config ---
  MANAGE_COLLEGE: 'MANAGE_COLLEGE',        // Modify college details, logos, domains
  MANAGE_USERS: 'MANAGE_USERS',            // Create/suspend any user
  MANAGE_ROLES: 'MANAGE_ROLES',            // Create roles and assign them to users
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',      // See who did what

  // --- Academic Setup ---
  MANAGE_ACADEMIC_YEARS: 'MANAGE_ACADEMIC_YEARS', 
  MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
  MANAGE_COURSES: 'MANAGE_COURSES',
  MANAGE_SUBJECTS: 'MANAGE_SUBJECTS',
  MANAGE_BATCHES: 'MANAGE_BATCHES',

  // --- Execution & Operations ---
  VIEW_TIMETABLE: 'VIEW_TIMETABLE',
  CREATE_TIMETABLE: 'CREATE_TIMETABLE',
  APPROVE_TIMETABLE: 'APPROVE_TIMETABLE',  // specific elevated permission (HOD/Director)

  VIEW_ATTENDANCE_ANALYTICS: 'VIEW_ATTENDANCE_ANALYTICS',
  MARK_ATTENDANCE: 'MARK_ATTENDANCE',      // Should technically only belong to Faculty

  // --- Exams & Results ---
  MANAGE_EXAM_SCHEDULE: 'MANAGE_EXAM_SCHEDULE',
  PUBLISH_RESULTS: 'PUBLISH_RESULTS',
  VIEW_RESULTS_ANALYTICS: 'VIEW_RESULTS_ANALYTICS',

  // --- Events & Broadcasting ---
  PUBLISH_NOTICES: 'PUBLISH_NOTICES',
  MANAGE_CALENDAR: 'MANAGE_CALENDAR',

  // --- Admissions & Finance ---
  MANAGE_ADMISSIONS: 'MANAGE_ADMISSIONS',
  MANAGE_FEES: 'MANAGE_FEES',
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',
};

// Default recommended permission sets that can be seeded
const DEFAULT_ROLE_GRANTS = {
  DIRECTOR: [
    ACTIONS.VIEW_AUDIT_LOGS, ACTIONS.VIEW_ATTENDANCE_ANALYTICS, ACTIONS.VIEW_RESULTS_ANALYTICS,
    ACTIONS.PUBLISH_NOTICES, ACTIONS.VIEW_FINANCIAL_REPORTS, ACTIONS.APPROVE_TIMETABLE
  ],
  HOD: [
    ACTIONS.MANAGE_SUBJECTS, ACTIONS.MANAGE_BATCHES, ACTIONS.CREATE_TIMETABLE, ACTIONS.APPROVE_TIMETABLE,
    ACTIONS.VIEW_ATTENDANCE_ANALYTICS, ACTIONS.PUBLISH_NOTICES, ACTIONS.MANAGE_EXAM_SCHEDULE
  ],
  FACULTY: [
    ACTIONS.VIEW_TIMETABLE, ACTIONS.MARK_ATTENDANCE
  ],
  ADMIN_STAFF: [
    ACTIONS.MANAGE_USERS, ACTIONS.MANAGE_ACADEMIC_YEARS, ACTIONS.MANAGE_DEPARTMENTS,
    ACTIONS.MANAGE_COURSES, ACTIONS.MANAGE_FEES, ACTIONS.MANAGE_ADMISSIONS, ACTIONS.MANAGE_CALENDAR
  ]
};

module.exports = {
  ACTIONS,
  DEFAULT_ROLE_GRANTS
};
